apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: dockerized-springboot-tomcat-buildah-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: dockerized-springboot-tomcat
  workspaces:
    - name: pipeline-shared-data
      persistentVolumeClaim:
        claimName: leo-liu-live-pvc-2nd
  